# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UI.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_HumonoidRobotControl(object):
    def setupUi(self, HumonoidRobotControl):
        HumonoidRobotControl.setObjectName("HumonoidRobotControl")
        HumonoidRobotControl.resize(826, 698)
        self.centralwidget = QtWidgets.QWidget(HumonoidRobotControl)
        self.centralwidget.setStyleSheet("#DownSide{\n"
" background-color: rgb(45, 91, 104);\n"
"}\n"
"#UpUp{\n"
" background-color:rgb(47, 91, 104);\n"
"}\n"
"\n"
"#UpSide{\n"
" background-color: rgb(255, 255, 255);\n"
"}\n"
"#MiddleLeft{\n"
" background-color: rgb(45, 91, 104);\n"
"}\n"
"#MiddleRight{\n"
" background-color: rgb(45, 91, 104);\n"
"}\n"
"\n"
"#Status{\n"
" background-color: rgb(255, 255, 0);\n"
"}\n"
"#MiddleDown{\n"
"    background-color: rgb(47, 91, 104);\n"
"}")
        self.centralwidget.setObjectName("centralwidget")
        self.UpSide = QtWidgets.QWidget(self.centralwidget)
        self.UpSide.setGeometry(QtCore.QRect(0, -10, 831, 551))
        self.UpSide.setObjectName("UpSide")
        self.UpMiddle = QtWidgets.QWidget(self.UpSide)
        self.UpMiddle.setGeometry(QtCore.QRect(0, 50, 831, 501))
        self.UpMiddle.setObjectName("UpMiddle")
        self.MiddleLeft = QtWidgets.QWidget(self.UpMiddle)
        self.MiddleLeft.setGeometry(QtCore.QRect(0, 0, 20, 501))
        self.MiddleLeft.setObjectName("MiddleLeft")
        self.Middle = QtWidgets.QWidget(self.UpMiddle)
        self.Middle.setGeometry(QtCore.QRect(20, 20, 791, 441))
        self.Middle.setObjectName("Middle")
        self.FeedLabel = QtWidgets.QLabel(self.Middle)
        self.FeedLabel.setGeometry(QtCore.QRect(0, 0, 791, 441))
        self.FeedLabel.setText("")
        self.FeedLabel.setObjectName("FeedLabel")
        self.MiddleRight = QtWidgets.QWidget(self.UpMiddle)
        self.MiddleRight.setGeometry(QtCore.QRect(810, 0, 20, 501))
        self.MiddleRight.setObjectName("MiddleRight")
        self.MiddleDown = QtWidgets.QWidget(self.UpMiddle)
        self.MiddleDown.setGeometry(QtCore.QRect(0, 460, 827, 41))
        self.MiddleDown.setObjectName("MiddleDown")
        self.Status = QtWidgets.QWidget(self.MiddleDown)
        self.Status.setGeometry(QtCore.QRect(90, 0, 641, 41))
        self.Status.setObjectName("Status")
        self.statusText = QtWidgets.QLineEdit(self.Status)
        self.statusText.setGeometry(QtCore.QRect(0, 5, 641, 29))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.statusText.setFont(font)
        self.statusText.setAlignment(QtCore.Qt.AlignCenter)
        self.statusText.setReadOnly(True)
        self.statusText.setObjectName("statusText")
        self.UpUp = QtWidgets.QWidget(self.UpSide)
        self.UpUp.setGeometry(QtCore.QRect(0, 10, 831, 61))
        self.UpUp.setObjectName("UpUp")
        self.Title = QtWidgets.QLineEdit(self.UpUp)
        self.Title.setGeometry(QtCore.QRect(120, 15, 591, 31))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Title.sizePolicy().hasHeightForWidth())
        self.Title.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(18)
        font.setBold(True)
        self.Title.setFont(font)
        self.Title.setAutoFillBackground(False)
        self.Title.setAlignment(QtCore.Qt.AlignCenter)
        self.Title.setReadOnly(True)
        self.Title.setObjectName("Title")
        self.DownSide = QtWidgets.QWidget(self.centralwidget)
        self.DownSide.setGeometry(QtCore.QRect(0, 540, 831, 131))
        self.DownSide.setObjectName("DownSide")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.DownSide)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.BodyComponents = QtWidgets.QWidget(self.DownSide)
        self.BodyComponents.setObjectName("BodyComponents")
        self.bodyComponentsText = QtWidgets.QLineEdit(self.BodyComponents)
        self.bodyComponentsText.setGeometry(QtCore.QRect(90, 10, 261, 31))
        self.bodyComponentsText.setAutoFillBackground(False)
        self.bodyComponentsText.setAlignment(QtCore.Qt.AlignCenter)
        self.bodyComponentsText.setReadOnly(True)
        self.bodyComponentsText.setObjectName("bodyComponentsText")
        self.Head = QtWidgets.QCheckBox(self.BodyComponents)
        self.Head.setGeometry(QtCore.QRect(110, 50, 91, 21))
        self.Head.setChecked(True)
        self.Head.setObjectName("Head")
        self.Elbows = QtWidgets.QCheckBox(self.BodyComponents)
        self.Elbows.setGeometry(QtCore.QRect(250, 80, 91, 21))
        self.Elbows.setChecked(True)
        self.Elbows.setObjectName("Elbows")
        self.Hands = QtWidgets.QCheckBox(self.BodyComponents)
        self.Hands.setGeometry(QtCore.QRect(110, 80, 91, 21))
        self.Hands.setChecked(True)
        self.Hands.setObjectName("Hands")
        self.Shoulders = QtWidgets.QCheckBox(self.BodyComponents)
        self.Shoulders.setGeometry(QtCore.QRect(250, 50, 91, 21))
        self.Shoulders.setChecked(True)
        self.Shoulders.setObjectName("Shoulders")
        self.horizontalLayout.addWidget(self.BodyComponents)
        self.ScreenSettings = QtWidgets.QWidget(self.DownSide)
        self.ScreenSettings.setObjectName("ScreenSettings")
        self.ScreenSettingsText = QtWidgets.QLineEdit(self.ScreenSettings)
        self.ScreenSettingsText.setGeometry(QtCore.QRect(50, 10, 261, 31))
        self.ScreenSettingsText.setAlignment(QtCore.Qt.AlignCenter)
        self.ScreenSettingsText.setReadOnly(True)
        self.ScreenSettingsText.setObjectName("ScreenSettingsText")
        self.BlackBackground = QtWidgets.QCheckBox(self.ScreenSettings)
        self.BlackBackground.setGeometry(QtCore.QRect(60, 50, 131, 21))
        self.BlackBackground.setChecked(False)
        self.BlackBackground.setObjectName("BlackBackground")
        self.HeadInfo = QtWidgets.QCheckBox(self.ScreenSettings)
        self.HeadInfo.setGeometry(QtCore.QRect(220, 50, 91, 21))
        self.HeadInfo.setChecked(True)
        self.HeadInfo.setObjectName("HeadInfo")
        self.HandsInfo = QtWidgets.QCheckBox(self.ScreenSettings)
        self.HandsInfo.setGeometry(QtCore.QRect(220, 80, 91, 21))
        self.HandsInfo.setChecked(True)
        self.HandsInfo.setObjectName("HandsInfo")
        self.UpperBodyInfo = QtWidgets.QCheckBox(self.ScreenSettings)
        self.UpperBodyInfo.setGeometry(QtCore.QRect(60, 80, 131, 21))
        self.UpperBodyInfo.setChecked(True)
        self.UpperBodyInfo.setObjectName("UpperBodyInfo")
        self.horizontalLayout.addWidget(self.ScreenSettings)
        HumonoidRobotControl.setCentralWidget(self.centralwidget)
        self.statusBar = QtWidgets.QStatusBar(HumonoidRobotControl)
        self.statusBar.setObjectName("statusBar")
        HumonoidRobotControl.setStatusBar(self.statusBar)

        self.retranslateUi(HumonoidRobotControl)
        QtCore.QMetaObject.connectSlotsByName(HumonoidRobotControl)

    def retranslateUi(self, HumonoidRobotControl):
        _translate = QtCore.QCoreApplication.translate
        HumonoidRobotControl.setWindowTitle(_translate("HumonoidRobotControl", "MainWindow"))
        self.statusText.setPlaceholderText(_translate("HumonoidRobotControl", "Status"))
        self.Title.setText(_translate("HumonoidRobotControl", "Humanoid Robot Control From Human Joint Angles Via 2D Camera"))
        self.bodyComponentsText.setText(_translate("HumonoidRobotControl", "Robot Body Components"))
        self.Head.setText(_translate("HumonoidRobotControl", "Head"))
        self.Elbows.setText(_translate("HumonoidRobotControl", "Elbows"))
        self.Hands.setText(_translate("HumonoidRobotControl", "Hands"))
        self.Shoulders.setText(_translate("HumonoidRobotControl", "Shoulders"))
        self.ScreenSettingsText.setText(_translate("HumonoidRobotControl", "Screen Settings"))
        self.BlackBackground.setText(_translate("HumonoidRobotControl", "Black Background"))
        self.HeadInfo.setText(_translate("HumonoidRobotControl", "Head Info"))
        self.HandsInfo.setText(_translate("HumonoidRobotControl", "Hands Info"))
        self.UpperBodyInfo.setText(_translate("HumonoidRobotControl", "Upper Body Info"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    HumonoidRobotControl = QtWidgets.QMainWindow()
    ui = Ui_HumonoidRobotControl()
    ui.setupUi(HumonoidRobotControl)
    HumonoidRobotControl.show()
    sys.exit(app.exec_())
